/**
 * Calendar Event Types
 *
 * Three types for the calendar feature:
 * - CalendarEvent: Persistent user-created events (stored in AsyncStorage)
 * - VirtualCalendarEvent: Computed events from existing data (not persisted)
 * - CalendarDisplayEvent: Discriminated union for unified UI rendering
 */

/** Calendar event type */
export type CalendarEventType = 'appointment' | 'schedule';

/** Virtual event source */
export type VirtualEventSource = 'invoice_due' | 'estimate_valid_until' | 'work_log';

/**
 * Persistent calendar event (stored in AsyncStorage)
 *
 * Created/edited/deleted by the user.
 * All dates are 'YYYY-MM-DD' strings, times are 'HH:MM' or null (all-day).
 */
export interface CalendarEvent {
  id: string;
  title: string;
  date: string;              // 'YYYY-MM-DD'
  startTime: string | null;  // 'HH:MM' or null (all-day)
  endTime: string | null;    // 'HH:MM' or null
  type: CalendarEventType;
  color: string;
  customerId: string | null;
  note: string | null;
  createdAt: number;         // epoch ms
  updatedAt: number;         // epoch ms
}

/**
 * Computed virtual event (not persisted)
 *
 * Generated from existing data: invoice due dates, estimate validity, work logs.
 * Read-only — tapping navigates to source document/log.
 */
export interface VirtualCalendarEvent {
  id: string;               // e.g. 'inv-123-due', 'est-456-valid', 'wl-789-worklog'
  title: string;            // e.g. '支払期限: INV-001'
  date: string;             // 'YYYY-MM-DD'
  startTime: null;          // Always all-day
  endTime: null;
  kind: 'virtual';
  source: VirtualEventSource;
  color: string;            // Source-specific color
  sourceDocumentId: string; // Reference to source document/work log ID
}

/**
 * Discriminated union for calendar UI
 *
 * Use `kind` to distinguish:
 * - 'user': Persistent event (create/edit/delete allowed)
 * - 'virtual': Computed event (read-only, tap navigates to source)
 */
export type CalendarDisplayEvent =
  | (CalendarEvent & { kind: 'user' })
  | VirtualCalendarEvent;

/**
 * Input for creating a new CalendarEvent
 * id, createdAt, updatedAt are auto-generated by the service.
 */
export interface CreateCalendarEventInput {
  title: string;
  date: string;
  startTime?: string | null;
  endTime?: string | null;
  type: CalendarEventType;
  color: string;
  customerId?: string | null;
  note?: string | null;
}

/**
 * Input for updating an existing CalendarEvent
 * Only specified fields are updated. updatedAt is auto-refreshed.
 */
export interface UpdateCalendarEventInput {
  title?: string;
  date?: string;
  startTime?: string | null;
  endTime?: string | null;
  type?: CalendarEventType;
  color?: string;
  customerId?: string | null;
  note?: string | null;
}
